default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: jp_companies_web_development

test:
  <<: *default
  database: jp_companies_web_test

production:
  <<: *default
  database: jp_companies_web_production
  username: jp_companies_web
  password: <%= ENV['JP_COMPANIES_WEB_DATABASE_PASSWORD'] %>
